// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pigeon/protocol.proto

package pigeon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// v1.0.0
// protocol
type Proto struct {
	DataLen              uint32   `protobuf:"varint,1,opt,name=dataLen,proto3" json:"dataLen,omitempty"`
	Op                   uint32   `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Ver                  uint32   `protobuf:"varint,3,opt,name=ver,proto3" json:"ver,omitempty"`
	Seq                  uint32   `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9355d5bdc98310a, []int{0}
}

func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (m *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(m, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetDataLen() uint32 {
	if m != nil {
		return m.DataLen
	}
	return 0
}

func (m *Proto) GetOp() uint32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetVer() uint32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Proto)(nil), "proto.protocol.Proto")
}

func init() {
	proto.RegisterFile("pigeon/protocol.proto", fileDescriptor_b9355d5bdc98310a)
}

var fileDescriptor_b9355d5bdc98310a = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xc8, 0x4c, 0x4f,
	0xcd, 0xcf, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0xf8,
	0xc0, 0x94, 0x1e, 0x4c, 0x54, 0x29, 0x93, 0x8b, 0x35, 0x00, 0x2c, 0x21, 0xc1, 0xc5, 0x9e, 0x92,
	0x58, 0x92, 0xe8, 0x93, 0x9a, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1b, 0x04, 0xe3, 0x0a, 0xf1,
	0x71, 0x31, 0xe5, 0x17, 0x48, 0x30, 0x81, 0x05, 0x99, 0xf2, 0x0b, 0x84, 0x04, 0xb8, 0x98, 0xcb,
	0x52, 0x8b, 0x24, 0x98, 0xc1, 0x02, 0x20, 0x26, 0x48, 0xa4, 0x38, 0xb5, 0x50, 0x82, 0x05, 0x22,
	0x52, 0x9c, 0x5a, 0x28, 0x24, 0xc4, 0xc5, 0x92, 0x94, 0x9f, 0x52, 0x29, 0xc1, 0xaa, 0xc0, 0xa8,
	0xc1, 0x13, 0x04, 0x66, 0x3b, 0x29, 0x44, 0xc9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25,
	0xe7, 0xe7, 0xea, 0x97, 0x97, 0xa7, 0xe6, 0xa5, 0xa7, 0x43, 0x9c, 0xa7, 0x0f, 0x71, 0x6b, 0x12,
	0x1b, 0x98, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x96, 0x5b, 0xbf, 0xbc, 0x00, 0x00,
	0x00,
}
