// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumErr int32

const (
	EnumErr_DEFAULT     EnumErr = 0
	EnumErr_SUCCESS     EnumErr = 200
	EnumErr_ServerError EnumErr = 1
	// pigeon
	EnumErr_JoinRoomErr EnumErr = 201
	// rainbow
	EnumErr_AuthErr EnumErr = 8001
)

var EnumErr_name = map[int32]string{
	0:    "DEFAULT",
	200:  "SUCCESS",
	1:    "ServerError",
	201:  "JoinRoomErr",
	8001: "AuthErr",
}

var EnumErr_value = map[string]int32{
	"DEFAULT":     0,
	"SUCCESS":     200,
	"ServerError": 1,
	"JoinRoomErr": 201,
	"AuthErr":     8001,
}

func (x EnumErr) String() string {
	return proto.EnumName(EnumErr_name, int32(x))
}

func (EnumErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Err struct {
	Err                  EnumErr  `protobuf:"varint,1,opt,name=err,proto3,enum=proto.common.EnumErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Err) Reset()         { *m = Err{} }
func (m *Err) String() string { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()    {}
func (*Err) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *Err) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Err.Unmarshal(m, b)
}
func (m *Err) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Err.Marshal(b, m, deterministic)
}
func (m *Err) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Err.Merge(m, src)
}
func (m *Err) XXX_Size() int {
	return xxx_messageInfo_Err.Size(m)
}
func (m *Err) XXX_DiscardUnknown() {
	xxx_messageInfo_Err.DiscardUnknown(m)
}

var xxx_messageInfo_Err proto.InternalMessageInfo

func (m *Err) GetErr() EnumErr {
	if m != nil {
		return m.Err
	}
	return EnumErr_DEFAULT
}

type LoginArgs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginArgs) Reset()         { *m = LoginArgs{} }
func (m *LoginArgs) String() string { return proto.CompactTextString(m) }
func (*LoginArgs) ProtoMessage()    {}
func (*LoginArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *LoginArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginArgs.Unmarshal(m, b)
}
func (m *LoginArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginArgs.Marshal(b, m, deterministic)
}
func (m *LoginArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginArgs.Merge(m, src)
}
func (m *LoginArgs) XXX_Size() int {
	return xxx_messageInfo_LoginArgs.Size(m)
}
func (m *LoginArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginArgs.DiscardUnknown(m)
}

var xxx_messageInfo_LoginArgs proto.InternalMessageInfo

func (m *LoginArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoginArgs) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type LoginReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReply) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.common.EnumErr", EnumErr_name, EnumErr_value)
	proto.RegisterType((*Empty)(nil), "proto.common.Empty")
	proto.RegisterType((*Err)(nil), "proto.common.Err")
	proto.RegisterType((*LoginArgs)(nil), "proto.common.LoginArgs")
	proto.RegisterType((*LoginReply)(nil), "proto.common.LoginReply")
}

func init() {
	proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6)
}

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x51, 0x1b, 0xf5, 0x52, 0x81, 0x65, 0x3e, 0xd4, 0x09, 0x55, 0x59, 0x40, 0x0c,
	0x8e, 0x04, 0x62, 0x61, 0x40, 0x0a, 0xc5, 0x0c, 0xa8, 0x53, 0x42, 0x16, 0xc6, 0x56, 0x96, 0x1b,
	0x95, 0xf8, 0xa2, 0xab, 0x43, 0x95, 0x9f, 0xc7, 0x06, 0xff, 0x0a, 0xd9, 0xc9, 0xc0, 0xd2, 0xe9,
	0xfc, 0x9c, 0xde, 0x47, 0xf2, 0x7b, 0x70, 0xb6, 0xc6, 0xba, 0x46, 0x93, 0xf6, 0x43, 0x34, 0x84,
	0x16, 0xf9, 0xd4, 0x0f, 0xd1, 0xef, 0x92, 0x08, 0x46, 0xb2, 0x6e, 0x6c, 0x97, 0x08, 0x08, 0x25,
	0x11, 0xbf, 0x86, 0x50, 0x11, 0xcd, 0x82, 0x79, 0x70, 0x73, 0x72, 0x77, 0x21, 0xfe, 0x67, 0x85,
	0x34, 0x6d, 0x2d, 0x89, 0x72, 0x97, 0x48, 0x1e, 0x60, 0xb2, 0x44, 0x5d, 0x99, 0x8c, 0xf4, 0x8e,
	0x33, 0x08, 0xb7, 0xaa, 0xf3, 0xd6, 0x24, 0x77, 0x4f, 0x7e, 0x09, 0xe3, 0x9d, 0x5a, 0x93, 0xb2,
	0xb3, 0x63, 0xbf, 0x1c, 0x28, 0x79, 0x04, 0xf0, 0x5a, 0xae, 0x9a, 0xcf, 0x8e, 0x9f, 0xc3, 0xc8,
	0xe2, 0x56, 0x99, 0xc1, 0xec, 0xe1, 0x90, 0x7b, 0x5b, 0x42, 0x34, 0x7c, 0x81, 0xc7, 0x10, 0xbd,
	0xc8, 0xd7, 0xac, 0x5c, 0xbe, 0xb3, 0x23, 0x3e, 0x85, 0xa8, 0x28, 0x17, 0x0b, 0x59, 0x14, 0xec,
	0x27, 0xe0, 0xa7, 0x10, 0x17, 0x8a, 0xbe, 0x14, 0x49, 0x22, 0x24, 0x16, 0x70, 0x06, 0xf1, 0x1b,
	0x56, 0x26, 0x47, 0x74, 0x2a, 0xfb, 0x0d, 0x9c, 0x90, 0xb5, 0x76, 0xe3, 0xe8, 0xfb, 0xe9, 0x79,
	0xfe, 0x71, 0xa5, 0x2b, 0xbb, 0x69, 0x57, 0xae, 0x67, 0xba, 0xdf, 0x2b, 0xa3, 0x75, 0xea, 0x8b,
	0x0f, 0x87, 0x5b, 0x8d, 0x3d, 0xdd, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x85, 0x5b, 0xa6,
	0x50, 0x01, 0x00, 0x00,
}
