// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumErr int32

const (
	EnumErr_SUCCESS EnumErr = 0
	// pigeon
	EnumErr_JoinRoomErr EnumErr = 201
)

var EnumErr_name = map[int32]string{
	0:   "SUCCESS",
	201: "JoinRoomErr",
}

var EnumErr_value = map[string]int32{
	"SUCCESS":     0,
	"JoinRoomErr": 201,
}

func (x EnumErr) String() string {
	return proto.EnumName(EnumErr_name, int32(x))
}

func (EnumErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Err struct {
	Err                  EnumErr  `protobuf:"varint,1,opt,name=err,proto3,enum=proto.common.EnumErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Err) Reset()         { *m = Err{} }
func (m *Err) String() string { return proto.CompactTextString(m) }
func (*Err) ProtoMessage()    {}
func (*Err) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *Err) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Err.Unmarshal(m, b)
}
func (m *Err) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Err.Marshal(b, m, deterministic)
}
func (m *Err) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Err.Merge(m, src)
}
func (m *Err) XXX_Size() int {
	return xxx_messageInfo_Err.Size(m)
}
func (m *Err) XXX_DiscardUnknown() {
	xxx_messageInfo_Err.DiscardUnknown(m)
}

var xxx_messageInfo_Err proto.InternalMessageInfo

func (m *Err) GetErr() EnumErr {
	if m != nil {
		return m.Err
	}
	return EnumErr_SUCCESS
}

func init() {
	proto.RegisterEnum("proto.common.EnumErr", EnumErr_name, EnumErr_value)
	proto.RegisterType((*Empty)(nil), "proto.common.Empty")
	proto.RegisterType((*Err)(nil), "proto.common.Err")
}

func init() {
	proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6)
}

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x60, 0x4a, 0x0f,
	0x22, 0xa6, 0xc4, 0xce, 0xc5, 0xea, 0x9a, 0x5b, 0x50, 0x52, 0xa9, 0xa4, 0xc7, 0xc5, 0xec, 0x5a,
	0x54, 0x24, 0xa4, 0xce, 0xc5, 0x9c, 0x5a, 0x54, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24,
	0xaa, 0x87, 0xac, 0x56, 0xcf, 0x35, 0xaf, 0x34, 0xd7, 0xb5, 0xa8, 0x28, 0x08, 0xa4, 0x42, 0x4b,
	0x83, 0x8b, 0x1d, 0xca, 0x17, 0xe2, 0xe6, 0x62, 0x0f, 0x0e, 0x75, 0x76, 0x76, 0x0d, 0x0e, 0x16,
	0x60, 0x10, 0x12, 0xe0, 0xe2, 0xf6, 0xca, 0xcf, 0xcc, 0x0b, 0xca, 0xcf, 0x07, 0xc9, 0x09, 0x9c,
	0x64, 0x74, 0x52, 0x88, 0x92, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0x02, 0x99, 0xa3, 0x5f, 0x5e,
	0x9e, 0x9a, 0x97, 0x9e, 0xae, 0x0f, 0x36, 0x18, 0xea, 0xb0, 0x24, 0x36, 0x30, 0xcf, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x31, 0xe1, 0x24, 0x06, 0xb0, 0x00, 0x00, 0x00,
}
